run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  govet:
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G104 # unhandled errors in deferred calls

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters: [errcheck]
      source: "fmt\\.Fprint|Flush\\(\\)|Close\\(\\)"
    - linters: [errcheck]
      path: "_test\\.go"
    - linters: [gosec]
      text: "G304"
    - linters: [gosec]
      text: "G115"
