{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "restore-drill.fullname" . }}
  labels:
    {{- include "restore-drill.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "restore-drill.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
